<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosUser\Authentication\Adapter\Doctrine'         => __DIR__ . '/src/Authentication/Adapter/Doctrine.php',
    'LosUser\Authentication\Storage\Doctrine'         => __DIR__ . '/src/Authentication/Storage/Doctrine.php',
    'Usuario\Controller\ConsoleController'            => __DIR__ . '/src/Controller/ConsoleController.php',
    'LosUser\Controller\Plugin\LosUserAuthentication' => __DIR__ . '/src/Controller/Plugin/LosUserAuthentication.php',
    'LosUser\Controller\UserController'               => __DIR__ . '/src/Controller/UserController.php',
    'LosUser\Entity\AbstractUser'                     => __DIR__ . '/src/Entity/AbstractUser.php',
    'LosUser\Entity\Access'                           => __DIR__ . '/src/Entity/Acesso.php',
    'LosUser\Entity\User'                             => __DIR__ . '/src/Entity/User.php',
    'LosUser\Entity\UserInterface'                    => __DIR__ . '/src/Entity/UserInterface.php',
    'LosUser\Form\Login'                              => __DIR__ . '/src/Form/Login.php',
    'LosUser\Form\LoginFilter'                        => __DIR__ . '/src/Form/LoginFilter.php',
    'LosUser\Module'                                  => __DIR__ . '/src/Module.php',
    'LosUser\Options\ControllerOptionsInterface'      => __DIR__ . '/src/Options/ControllerOptionsInterface.php',
    'LosUser\Options\IdentityOptionsInterface'        => __DIR__ . '/src/Options/IdentityOptionsInterface.php',
    'LosUser\Options\ModuleOptions'                   => __DIR__ . '/src/Options/ModuleOptions.php',
    'LosUser\Options\ServiceOptionsInterface'         => __DIR__ . '/src/Options/ServiceOptionsInterface.php',
    'Usuario\Service\Usuario'                         => __DIR__ . '/src/Service/Usuario.php',
    'LosUser\View\Helper\LosUserIdentity'             => __DIR__ . '/src/View/Helper/LosUserIdentity.php',
);
